include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME		= MighfManager
PACKAGE_NAME	= MighfManager

MighfManager_APPLICATION_ICON = icon.tiff
# MighfManager_MAIN_MODEL_FILE  = UserInterface.nib

MighfManager_OBJC_FILES= \
			main.mm
#			MHFFileSystem.m \
			MHFBIOS.m \
			NSTextView+additions.m

include $(GNUSTEP_MAKEFILES)/application.make
